baseurl: ""
siteurl: "https://kindasimplesolutions.com"

## Dependencies
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "prettify"]

remote_theme: mmistakes/minimal-mistakes@4.24.0
repository: kindasimple/kindasimple.github.io
minimal_mistakes_skin: "dark"
logo: "/assets/images/88x88.png"

author:
  name: "Evan White"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Experienced Tech Leader Specializing in Mobile Development, Compute Platforms & Business Applications"
  location : "Bay Area, CA"
  links:
    - label: "kindasimple"
      icon: "fas fa-fw fa-link"
      url: "http://kindasimple.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kindasimple"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kindasimple"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/kindasimple"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kindasimple/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kindasimple"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kindasimple"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/kindasimple"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kindasimple/"

## Permalinks
permalink:     '/blog/:title/'
relative_permalinks: false

## Server
#destination:      ./_gh_pages
exclude:          [".gitignore", "CNAME", "CNAME", "LICENSE", "params.json", "README.md", "serve.cmd", 'node_modules']
include:            ['_pages']
#port:             9001

plugins:
  - jekyll-sitemap
  - jekyll-include-cache
  - minimal-mistakes-jekyll

## Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: true
  syntax_highlighter_opts:
    block:
      line_numbers: inline
      line_numbers_start: 1
      tab_width: 4
      bold_every: 10
      css: style

## Custom vars
title: "Kinda Simple Solutions"
description: Experienced Tech Leader Specializing in Mobile Development, Compute Platforms & Business Applications | Expertise in AWS, .NET, Agile

authors:
  evan:
    display_name: Evan White
    gravatar: ae943e5c7ca9f2846df1064e5b569d2d
    email: kindasimple@gmail.com
    web: http://www.kindasimple.com/
    twitter: kindasimple
    github: kindasimple
