## Dependencies
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "prettify"]


## Permalinks
permalink:     '/blog/:title/'
relative_permalinks: false

## Server
#destination:      ./_gh_pages
exclude:          [".gitignore", "CNAME", "CNAME", "LICENSE", "params.json", "README.md", "serve.cmd", 'node_modules']
include:            ['_pages']
#port:             9001

gems:
  - jekyll-sitemap

## Defaults
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "blog"
      author: Evan

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: true
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

## Custom vars
name: KindaSimple Solutions
description: The projects

## Navigation
nav-about:	/about
nav-recollection-wp:            /MajorSystem
nav-pgh_techfest-wp:          /PGHTechFest
nav-archives:	/archive
nav-projects:	/projects
nav-rss:		/blog/feed.xml
nav-blog:		/blog

link-base_url:           	/
link-github:             	https://github.com/kindasimple
link-stack_overflow:     	http://stackoverflow.com/users/491506/kindasimple
link-stack_overflow-avatar: http://stackoverflow.com/users/flair/491506.png
link-twitter:            	https://twitter.com/kindasimple
link-coderbits:          	https://coderbits.com/kindasimple
link-blog:               	http://kindasimplesolutions.com/blog
link-url:                	http://kindasimplesolutions.com
link-pgh_techfest-code:     https://github.com/kindasimple/PGHTechFest
link-pgh_techfest-win8:     http://apps.microsoft.com/windows/en-us/app/pghtechfest/630784e7-6037-494c-94d8-6eea9f468125
link-pgh_techfest-wp8:		http://www.windowsphone.com/en-us/store/app/pghtechfest/bdd8a816-173b-4b2e-9296-978e88053605
link-recollection-win8:     http://apps.microsoft.com/windows/en-us/app/699fe4c9-13a8-4ff7-b2df-d6cae8802f83
link-recollection-wp8:      http://www.windowsphone.com/en-us/store/app/recollection/8de271b5-437c-4a26-b2cd-987148b4955b
link-recollection-web:      http://mnemonal.com
link-big_arms_club-web:		http://bigarmsclub.com
email-link:					mailto:kindasimple@gmail.com
email-text:					kindasimple@gmail.com

authors:
  evan:
    display_name: Evan White
    gravatar: ae943e5c7ca9f2846df1064e5b569d2d
    email: kindasimple@gmail.com
    web: http://www.kindasimple.com/
    twitter: kindasimple
    github: kindasimple
